# Generated by Django 4.2.16 on 2024-11-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonationpost',
            name='urgency',
            field=models.CharField(choices=[('Low', 'low'), ('Medium', 'medium'), ('High', 'high')], default='Medium', max_length=20),
        ),
    ]
