# Generated by Django 4.2.16 on 2024-11-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
