# Generated by Django 4.2.16 on 2024-11-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
