# Generated by Django 5.1.3 on 2026-05-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_share_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
