# Generated by Django 4.2.16 on 2024-11-14 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_community_textpost_linkpost_imagepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.imagepost')),
                ('post_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.linkpost')),
                ('post_text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.textpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
