# Generated by Django 4.2.16 on 2024-11-14 17:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('link', 'Link'), ('image', 'Image'), ('text', 'Text')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='community',
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='linkpost',
            name='community',
        ),
        migrations.RemoveField(
            model_name='linkpost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='textpost',
            name='community',
        ),
        migrations.RemoveField(
            model_name='textpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='ImagePost',
        ),
        migrations.DeleteModel(
            name='LinkPost',
        ),
        migrations.DeleteModel(
            name='TextPost',
        ),
    ]
