
### 
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
	"email": "test6",
	"password": "123456789012"
}

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
	"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMTc4MzQ2NCwiaWF0IjoxNzMxNjk3MDY0LCJqdGkiOiIwOGNhNWRhZTk3YjU0ODljOTVlYzUyNTI3YWUyN2E0ZCIsInVzZXJfaWQiOjF9.y1nv9u6sFwAAkEyLH6zMo-WMSCMlamZIPVM1Y1GQYlo"
}

###
POST http://localhost:8000/api/register/ HTTP/1.1
Content-Type: application/json

{
    "username": "test6",
    "email": "test6",
    "password": "123456789012"
}

###
GET http://localhost:8000/api/posts/study/ HTTP/1.1

###
GET http://localhost:8000/api/posts/carpool/ HTTP/1.1

###
GET http://localhost:8000/api/posts/blood-donation/ HTTP/1.1

###
GET http://localhost:8000/api/posts/latest/ HTTP/1.1


POST http://localhost:8000/api/createStudyPost/ HTTP/1.1
Content-Type: application/json

{
    "community": "Study Guide",
    "studytitle": "Calculus 101",
    "studyquestion": "What is the derivative of sin(x)?",
    "questionlink": "http://math.com/problem1",
    "questionimage": "http://math.com/images/problem1.jpg"
}


###
POST http://localhost:8000/api/createComment/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNTUxNDI3LCJpYXQiOjE3MzI1NDQyMjcsImp0aSI6ImY2MzEwZjM5YTAwMzQ2YTliZDEyNjViNTYwZjM0NGFmIiwidXNlcl9pZCI6N30.gZxnGvqSyxRoVEfUhum7tdV2dt7zYDeODge5E_g1spQ

{
    "post_id": 1,
    "content": "This is a test comment."
}

###
POST http://localhost:8000/api/createLike/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNTY3OTIxLCJpYXQiOjE3MzI1NjA3MjEsImp0aSI6IjBhYTAwMjYzN2E5NjRkNjk4MDQ2ZGExZTA4ZDgzNmZiIiwidXNlcl9pZCI6N30.Q5jPbaUpUtElbDEmpv5Po9YpYKgMBgxyyI5dwGUDAeQ

{
    "post_id": 14
}



