
### login
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
	"email": "new_email@example.com",
	"password": "new_secure_password"
}

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
	"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMTc4MzQ2NCwiaWF0IjoxNzMxNjk3MDY0LCJqdGkiOiIwOGNhNWRhZTk3YjU0ODljOTVlYzUyNTI3YWUyN2E0ZCIsInVzZXJfaWQiOjF9.y1nv9u6sFwAAkEyLH6zMo-WMSCMlamZIPVM1Y1GQYlo"
}

###
POST http://localhost:8000/api/register/ HTTP/1.1
Content-Type: application/json

{
    "username": "test6",
    "email": "test6",
    "password": "123456789012"
}

###
GET http://localhost:8000/api/posts/study/ HTTP/1.1

###
GET http://localhost:8000/api/posts/carpool/ HTTP/1.1

###
GET http://localhost:8000/api/posts/blood-donation/ HTTP/1.1

###
GET http://localhost:8000/api/posts/latest/ HTTP/1.1


POST http://localhost:8000/api/createStudyPost/ HTTP/1.1
Content-Type: application/json

{
    "community": "Study Guide",
    "studytitle": "Calculus 101",
    "studyquestion": "What is the derivative of sin(x)?",
    "questionlink": "http://math.com/problem1",
    "questionimage": "http://math.com/images/problem1.jpg"
}


###
POST http://localhost:8000/api/createComment/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNTcyNjkzLCJpYXQiOjE3MzI1NjU0OTMsImp0aSI6IjM2MGQ5MDQ2NDhiMDRiYWU4NzRlOTFjYWEyNWRjMTk1IiwidXNlcl9pZCI6Nn0.FmW_buQaF_buemzVW1Z3o1UFgO3oamhAIDA-LE4GRXE

{
    "post": 1,
    "content": "This is a test comment."
}

###
POST http://localhost:8000/api/createLike/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNTY3OTIxLCJpYXQiOjE3MzI1NjA3MjEsImp0aSI6IjBhYTAwMjYzN2E5NjRkNjk4MDQ2ZGExZTA4ZDgzNmZiIiwidXNlcl9pZCI6N30.Q5jPbaUpUtElbDEmpv5Po9YpYKgMBgxyyI5dwGUDAeQ

{
    "post_id": 14
}


###
POST http://localhost:8000/api/createShare/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNTczMzY2LCJpYXQiOjE3MzI1NjYxNjYsImp0aSI6IjhhZTYxNGMxOWNkOTRkOTRiN2QwYjU0ODlmYzU0Y2YyIiwidXNlcl9pZCI6Nn0.Q02dC-RwDdDMd6uVR_RHZSSuV6O0rD5-g6Rf3-LAoKA

{
    "post_id": 12,
    "content": "This is a test share."
}
### detail viewof user

GET http://localhost:8000/api/userDetail/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNjM3MzIwLCJpYXQiOjE3MzI2MzAxMjAsImp0aSI6ImM4YzZlMDZkNThiODQ3YTU5OGQ1YjM1NGJhYTlkMmU0IiwidXNlcl9pZCI6Nn0.gfK2R9tDUosGaDl0hmrsfv-Cbm0GRTRZKrvohJ3b9ls
Content-Type: application/json

### view user posts
GET http://localhost:8000/api/userPosts/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNjM4Njg0LCJpYXQiOjE3MzI2MzE0ODQsImp0aSI6IjZiZWY4YWFhODYzMjRjOTRhZjI0M2YwN2Q0YjM2ODI3IiwidXNlcl9pZCI6Mn0.XZbqXNx2BI43cYG0AcP-FoBabzTl1ir750zxNBfI_Sk
Content-Type: application/json


###update email
POST http://localhost:8000/api/updateProfile/email/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyODA0OTY0LCJpYXQiOjE3MzI3OTc3NjQsImp0aSI6IjY1NTUwYmQ5YmU1YzQ1ZmFiYzgzMmU3OTU4YzlkZmQ1IiwidXNlcl9pZCI6Mn0.DyMw4STM1LN4_jF8875eDsa38Q2O70EhkCu7_oRq8LE
Content-Type: application/json

{
    "email": "new_email@example.com"
}

###update password
POST http://localhost:8000/api/updateProfile/password/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyODA0OTY0LCJpYXQiOjE3MzI3OTc3NjQsImp0aSI6IjY1NTUwYmQ5YmU1YzQ1ZmFiYzgzMmU3OTU4YzlkZmQ1IiwidXNlcl9pZCI6Mn0.DyMw4STM1LN4_jF8875eDsa38Q2O70EhkCu7_oRq8LE
Content-Type: application/json

{
    "old_password": "123456789012",
    "new_password": "new_secure_password"
}
