import Header from "@/components/Header";
import "./globals.css";
import {NextUIProvider} from "@nextui-org/system";
import Sidebar from "@/components/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body >
     
          <Header />
        <div className="flex items-center">
          <Sidebar/>
          <div className="flex-1 bg-[#0E1113] min-h-screen">
            {children}
          </div>
        
        </div>
      </body>
      
    </html>
  );
}
