import Header from "@/components/Header";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { ThemeProvider } from "@/components/theme-provider"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="overflow-y-scroll no-scrollbar">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>

          <Header />
          <div className="flex items-center overflow-y-scroll no-scrollbar">
            <Sidebar />
            <div className="flex-1 bg-[#0E1113] min-h-screen overflow-y-scroll no-scrollbar">
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
